server:
  port: 8888 
  mode: debug
  salt: MyGO!!!!!
  dict:
    - /home/kori/go/pkg/mod/github.com/go-ego/gse@v0.80.2/data/dict/zh/s_1.txt
    - /home/kori/go/pkg/mod/github.com/go-ego/gse@v0.80.2/data/dict/zh/t_1.txt 

database:
  host: localhost
  port: 5432
  username: kori
  password: 123456
  dbName: mygo
  ssl: disable
  limit: 50

log:
  level: debug # Our server logs have five levels: fatal, error, warn, info, debug. When server mode is set as release, log level will be set with warn level automatically if this level is set lower than warn.
  console: true
  file: true
  sysPath: log/sys.log
  ginPath: log/gin.log
  format:
    prefix: MyGO
    timestamp: "2006-01-02 15:04:05"

jwt:
  tokenExpire: 60
  refreshExpire: 10
  secret: MyGO!!!!! is a bang team with five girls, Anno, Tomori, Soyo, Taki and Rena

blockchain:
  gethClient: http://172.18.0.50:8545
  keystorePath: /home/kori/blockchain/data/keystore
  contractAddress: 0x81aB3bcfA5afA7d2469c4002B0422834d2D45319
  ownerPassword: 123
  ownerAddress: 0x2659794f119bef5c81942c2afd9e4f9a99347fb3
