definitions:
  controller.TransferRequest:
    properties:
      amount:
        type: string
      passphrase:
        type: string
      toName:
        type: string
      username:
        type: string
    type: object
host: localhost:8888
info:
  contact:
    email: Miyohashikori457@gmail.com
    name: KoriSama
    url: https://kori-sama.github.io/
  description: This is a API docs for MyGO project.
  title: MyGO!!!!! API docs
  version: "0.1"
paths:
  /api/blockchain/createWallet/{username}/{passphrase}:
    post:
      description: create wallet in blockchain
      parameters:
      - description: username
        in: path
        name: username
        required: true
        type: string
      - description: passphrase
        in: path
        name: passphrase
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: create wallet
      tags:
      - blockchain
  /api/blockchain/getBalance/{username}:
    get:
      description: get balance amount from wallet
      parameters:
      - description: username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: get balance
      tags:
      - blockchain
  /api/blockchain/transfer:
    post:
      consumes:
      - application/json
      description: transfer funds from one wallet to another
      parameters:
      - description: transfer request json
        in: body
        name: transfer
        required: true
        schema:
          $ref: '#/definitions/controller.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: transfer funds
      tags:
      - blockchain
swagger: "2.0"
