name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./cmd/mygo
    
    - name: Upload
      uses: zhenyuWang/Upload-File-Action@v1.0.1
      with: 
        username: ${{ secrets.USERNAME }}
        server: ${{secrets.SERVER_URL}}
        port: 22
        ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
        local_file: ./mygo
        target_path: /home/${{secrets.USERNAME}}/mygo